project:
  type: website
  output-dir: docs

website:
  title: "Advanced GIS 486/687"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: labs/index.qmd
        text: Labs
      - href: project/index.qmd
        text: Final Project

format:
  html:
    theme: zephyr
    css: styles.css
    toc: true

editor: visual

