project:
  type: website
  output-dir: docs

website:
  title: "Advanced GIS 486/687"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: labs/lab1/index.qmd
        text: Lab 1
      - href: labs/lab2/index.qmd
        text: Lab 2
      - href: labs/lab3/index.qmd
        text: Lab 3

format:
  html:
    theme: zephyr
    css: styles.css
    toc: true

editor: visual

