project:
  type: website
  output-dir: docs

website:
  title: "Advanced GIS 486/687"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: labs/lab1/index.qmd
        text: Lab 1

format:
  html:
    theme: zephyr
    css: styles.css
    toc: true

editor: visual

