---
title: "Lab 1 - QGIS Intro"
format: html
---

## Lab 1 / Week 1

You'll need to carefully read the instructions to get everything installed correctly.

### Installation

-   Download and install QGIS on your computer: <https://www.qgis.org/en/site/>

    -   If you're on Windows, I highly recommend doing it through Chocolatey.

        -   Installing Chocolatey: <https://chocolatey.org/install>

        -   Installing QGIS in Chocolatey: <https://chocolatey.org/packages/QGIS>

-   Download and install R and RStudio (don't do this through Chocolatey).

    -   Install R: [https://cran.r-project.org/](https://cran.r-project.org/https://cran.r-project.org/)

    -   Install RStudio: <https://rstudio.com/products/rstudio/download/>

### Create a GitHub Account

-   Create an account on github.com

    -   Your username will be part of your URL later in the course, so pick something that is obviously you and that you wouldn't be embarrassed to show an employer.

### Making Maps

-   Reproduce maps in Chapters 2-4 in the Learn QGIS book.

    -   Find three maps that you'd like to embellish or add flair to customize the maps.
    -   Read the Preface to find the links to the QGIS sample data and the data for the book. If you can't find the data for the book, use this link to download the zip file (and extract!) the files: [https://drive.google.com/file/d/1mKJ6mtUhkUGXodS_KEZbRN0_ail1KJeE/view?usp=sharing](https://drive.google.com/file/d/1mKJ6mtUhkUGXodS_KEZbRN0_ail1KJeE/view?usp=sharinghttps://drive.google.com/file/d/1mKJ6mtUhkUGXodS_KEZbRN0_ail1KJeE/view?usp=sharing)

### Readings

-   Acquire the book *Computing Geographically: Bridging Giscience and Geography* by David O'Sullivan.

-   **Graduate students**: Please review and be conversant in how GIS can connect doing things in the world and uneven knowledge production. See especially the sections Ontology Research (starts page 731) and the Conclusion (starts page 735).

    -   Schuurman, Nadine. 2006. "Formalization Matters: Critical GIS and Ontology Research." *Annals of the Association of American Geographers* 96 (4): 726--39. <https://doi.org/10.1111/j.1467-8306.2006.00513.x>

::: {.alert .alert-info}
### What to turn-in

Turn in a single PDF that contains:

1.  A nicely formatted cover page with

    -   your name,

    -   your UMBC email address,

    -   your github name, and a link to your github profile (it's okay if nothing is there),

    -   your interests and how they relate to the course,

    -   inklings on a potential final project, and

    -   include any other material you think I need to know.

2.  Your three embellished maps. Challenge yourself. You can be creative and customize the cartography, but you could also add additional data. For each map, explain what you embellished and why pushed yourself to do it that way.

**Hint:** Use PDFSam (or install it with Chocolatey) to merge multiple PDFs together. For example, create a layout in QGIS and export those maps to PDF. Then use PDFSam to merge those files.
:::
